title: Rica Esquivel
description: >-
  Portfolio of Rica Esquivel - Computer Science undergraduate at Virginia Tech. 
  Showcasing technical projects, internships, leadership experience, and personal interests.
remote_theme: "mmistakes/minimal-mistakes"

include:
  - _pages

plugins:
  - jekyll-include-cache
  
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: true
      read_time: false

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true